/**
 * Generate a unified GitHub Actions CI pipeline integrating security checks.
 */

import { detectProject } from "../detector.js";

export function generateCiPipeline(projectPath: string): string {
  const info = detectProject(projectPath);
  const lang = (info.primaryLanguage || "").toLowerCase();

  const testStep = generateTestStep(lang);
  const lintStep = generateLintStep(lang);
  const auditStep = generateAuditStep(lang);

  return `# Unified Security CI Pipeline
# Generated by ossguard — combines testing, linting, CodeQL, and dependency audit.

name: CI Security Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  security-events: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
${testStep}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
${lintStep}

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${mapLanguageForCodeql(lang)}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  dependency-audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
${auditStep}

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
`;
}

function mapLanguageForCodeql(lang: string): string {
  const map: Record<string, string> = { python: "python", javascript: "javascript-typescript", typescript: "javascript-typescript", go: "go", java: "java-kotlin", kotlin: "java-kotlin", ruby: "ruby", "c++": "cpp", c: "cpp" };
  return map[lang] || "javascript-typescript";
}

function generateTestStep(lang: string): string {
  if (lang === "python") return `      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install -e ".[test]" || pip install -r requirements.txt
      - run: pytest --tb=short`;
  if (lang === "go") return `      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go test ./...`;
  if (lang === "rust") return `      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test`;
  return `      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test`;
}

function generateLintStep(lang: string): string {
  if (lang === "python") return `      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install ruff
      - run: ruff check .`;
  if (lang === "go") return `      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go vet ./...`;
  if (lang === "rust") return `      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: cargo clippy -- -D warnings`;
  return `      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx eslint . || true`;
}

function generateAuditStep(lang: string): string {
  if (lang === "python") return `      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install pip-audit
      - run: pip-audit`;
  if (lang === "go") return `      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: govulncheck ./...`;
  if (lang === "rust") return `      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-audit
      - run: cargo audit`;
  return `      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm audit --audit-level=high`;
}
