/**
 * SLSA provenance checker — assess Supply-chain Levels for Software Artifacts.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { detectProject, type ProjectInfo } from "../detector.js";

export interface SLSARequirement {
  id: string;
  level: number;
  description: string;
  status: string;
  evidence: string;
  recommendation: string;
}

export interface SLSAReport {
  requirements: SLSARequirement[];
  achievedLevel: number;
  metCount: number;
  totalCount: number;
  levelLabel: string;
}

const REQUIREMENTS: Array<[string, number, string]> = [
  ["slsa-l1-provenance", 1, "Build process MUST generate provenance describing how the artifact was built"],
  ["slsa-l1-ci", 1, "Build MUST run in a CI/CD system (not a developer workstation)"],
  ["slsa-l1-published", 1, "Provenance MUST be available to consumers"],
  ["slsa-l2-hosted", 2, "Build MUST run on a hosted build service"],
  ["slsa-l2-signed", 2, "Provenance MUST be signed (authenticated)"],
  ["slsa-l2-service-gen", 2, "Provenance MUST be generated by the build service itself"],
  ["slsa-l3-isolated", 3, "Build MUST run in an isolated, ephemeral environment"],
  ["slsa-l3-unforgeable", 3, "Provenance MUST be unforgeable (can't be modified by build job)"],
  ["slsa-l3-non-falsifiable", 3, "Build service MUST guarantee non-falsifiable provenance"],
  ["slsa-l4-hermetic", 4, "Build MUST be hermetic (no network access during build)"],
  ["slsa-l4-reproducible", 4, "Build SHOULD be reproducible"],
  ["slsa-l4-two-party", 4, "All changes require two-party review before merging"],
];

export function checkSlsa(projectPath: string): SLSAReport {
  const resolved = path.resolve(projectPath);
  const info = detectProject(resolved);

  const requirements: SLSARequirement[] = REQUIREMENTS.map(([id, level, description]) => {
    const [status, evidence, rec] = checkRequirement(id, info, resolved);
    return { id, level, description, status, evidence, recommendation: rec };
  });

  const met = requirements.filter((r) => r.status === "met").length;
  let achieved = 0;
  for (let lvl = 1; lvl <= 4; lvl++) {
    const lvlReqs = requirements.filter((r) => r.level === lvl);
    if (lvlReqs.length && lvlReqs.every((r) => r.status === "met")) achieved = lvl;
    else break;
  }

  return {
    requirements, achievedLevel: achieved, metCount: met, totalCount: requirements.length,
    levelLabel: achieved === 0 ? "SLSA Level 0 (No provenance)" : `SLSA Build Level ${achieved}`,
  };
}

function readWorkflows(base: string): Array<{ name: string; content: string }> {
  const wfDir = path.join(base, ".github", "workflows");
  if (!fs.existsSync(wfDir)) return [];
  return fs.readdirSync(wfDir).filter((f: string) => f.endsWith(".yml") || f.endsWith(".yaml")).map((f: string) => ({ name: f, content: fs.readFileSync(path.join(wfDir, f), "utf-8") }));
}

function checkRequirement(id: string, info: ProjectInfo, p: string): [string, string, string] {
  const wfs = () => readWorkflows(p);

  if (id === "slsa-l1-provenance") { for (const wf of wfs()) { const c = wf.content.toLowerCase(); if (["provenance", "slsa", "attest", "in-toto"].some((k) => c.includes(k))) return ["met", `Provenance generation found in ${wf.name}`, ""]; } return ["unmet", "", "Add SLSA provenance generation (e.g. slsa-framework/slsa-github-generator)"]; }
  if (id === "slsa-l1-ci") { if (info.hasGithubActions) return ["met", "GitHub Actions CI found", ""]; if ([".travis.yml", ".circleci/config.yml", "Jenkinsfile", ".gitlab-ci.yml"].some((f) => fs.existsSync(path.join(p, f)))) return ["met", "CI found", ""]; return ["unmet", "", "Set up CI/CD — run `ossguard ci`"]; }
  if (id === "slsa-l1-published") { for (const wf of wfs()) { const c = wf.content.toLowerCase(); if (c.includes("upload-artifact") || c.includes("release")) return ["met", "Artifacts published in CI", ""]; } return ["unknown", "", "Publish provenance alongside release artifacts"]; }

  if (id === "slsa-l2-hosted") { return info.hasGithubActions ? ["met", "GitHub Actions is a hosted build service", ""] : ["unknown", "", "Use a hosted CI service"]; }
  if (id === "slsa-l2-signed") { if (info.hasSigstore) return ["met", "Sigstore signing configured", ""]; for (const wf of wfs()) { const c = wf.content.toLowerCase(); if (["cosign", "sigstore", "sign", "attest"].some((k) => c.includes(k))) return ["met", `Signing found in ${wf.name}`, ""]; } return ["unmet", "", "Sign provenance with Sigstore — run `ossguard init`"]; }
  if (id === "slsa-l2-service-gen") { for (const wf of wfs()) { const c = wf.content.toLowerCase(); if (c.includes("slsa-github-generator") || c.includes("slsa-framework")) return ["met", "SLSA generator produces provenance", ""]; } return ["unmet", "", "Use slsa-framework/slsa-github-generator for service-generated provenance"]; }

  if (id === "slsa-l3-isolated") { return info.hasGithubActions ? ["met", "GitHub Actions runs on ephemeral VMs", ""] : ["unknown", "", "Ensure builds run in isolated, ephemeral environments"]; }
  if (id === "slsa-l3-unforgeable") { for (const wf of wfs()) { if (wf.content.toLowerCase().includes("slsa-github-generator")) return ["met", "SLSA generator produces unforgeable provenance", ""]; } return ["unmet", "", "Use SLSA generator for unforgeable provenance"]; }
  if (id === "slsa-l3-non-falsifiable") { for (const wf of wfs()) { if (wf.content.toLowerCase().includes("slsa-github-generator")) return ["met", "SLSA generator guarantees non-falsifiable provenance", ""]; } return ["unmet", "", "Ensure provenance is generated outside the build job"]; }

  if (id === "slsa-l4-hermetic") return ["unknown", "", "Verify builds are hermetic (no network access during build)"];
  if (id === "slsa-l4-reproducible") return ["unknown", "", "Verify builds are reproducible"];
  if (id === "slsa-l4-two-party") { const bp = path.join(p, "BRANCH_PROTECTION.md"); if (fs.existsSync(bp)) { try { const c = fs.readFileSync(bp, "utf-8").toLowerCase(); if (c.includes("review") && (c.includes("2") || c.includes("two"))) return ["met", "Two-party review documented", ""]; } catch {} } return ["unknown", "", "Require two-party review for all changes"]; }

  return ["unknown", "", ""];
}
